2025-06-05 17:30:36,270 - passlib.handlers.bcrypt - WARNING - (trapped) error reading bcrypt version
Traceback (most recent call last):
  File "C:\Users\HP\AppData\Local\Programs\Python\Python312\Lib\site-packages\passlib\handlers\bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
              ^^^^^^^^^^^^^^^^^
AttributeError: module 'bcrypt' has no attribute '__about__'
2025-06-10 12:49:24,870 - app.core.logging - ERROR - Failed to create system log: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UndefinedColumn) column "source" of relation "lead" does not exist
LINE 1: ...y, salesperson, sales_team, tags, internal_notes, source, pl...
                                                             ^

[SQL: INSERT INTO lead (name, probability, company_name, street, street2, city, state, zip_code, country, website, contact_name, contact_title, email, job_position, phone, mobile, line_id, age, customer_budget, product_interest, invoice_total, status, priority, salesperson, sales_team, tags, internal_notes, source, platform_id, assigned_user_id, created_at, updated_at) VALUES (%(name)s, %(probability)s, %(company_name)s, %(street)s, %(street2)s, %(city)s, %(state)s, %(zip_code)s, %(country)s, %(website)s, %(contact_name)s, %(contact_title)s, %(email)s, %(job_position)s, %(phone)s, %(mobile)s, %(line_id)s, %(age)s, %(customer_budget)s, %(product_interest)s, %(invoice_total)s, %(status)s, %(priority)s, %(salesperson)s, %(sales_team)s, %(tags)s, %(internal_notes)s, %(source)s, %(platform_id)s, %(assigned_user_id)s, %(created_at)s, %(updated_at)s) RETURNING lead.id]
[parameters: {'name': 'string', 'probability': 0.0, 'company_name': 'string', 'street': 'string', 'street2': 'string', 'city': 'string', 'state': 'string', 'zip_code': 'string', 'country': 'string', 'website': 'string', 'contact_name': 'string', 'contact_title': 'string', 'email': 'string', 'job_position': 'string', 'phone': 'string', 'mobile': 'string', 'line_id': 'string', 'age': 0, 'customer_budget': 'RANGE_1', 'product_interest': 'string', 'invoice_total': 0.0, 'status': 'NEW', 'priority': 0, 'salesperson': 'string', 'sales_team': 'string', 'tags': 'string', 'internal_notes': 'string', 'source': 'string', 'platform_id': 'string', 'assigned_user_id': None, 'created_at': datetime.datetime(2025, 6, 10, 5, 49, 24, 852206), 'updated_at': datetime.datetime(2025, 6, 10, 5, 49, 24, 852206)}]
(Background on this error at: https://sqlalche.me/e/20/f405) (Background on this error at: https://sqlalche.me/e/20/7s2a)
2025-06-10 13:03:56,754 - app.core.logging - ERROR - Failed to create system log: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (psycopg2.errors.UndefinedColumn) column "platform_id" of relation "lead" does not exist
LINE 1: ...person, sales_team, tags, internal_notes, source, platform_i...
                                                             ^

[SQL: INSERT INTO lead (name, probability, company_name, street, street2, city, state, zip_code, country, website, contact_name, contact_title, email, job_position, phone, mobile, line_id, age, customer_budget, product_interest, invoice_total, status, priority, salesperson, sales_team, tags, internal_notes, source, platform_id, assigned_user_id, created_at, updated_at) VALUES (%(name)s, %(probability)s, %(company_name)s, %(street)s, %(street2)s, %(city)s, %(state)s, %(zip_code)s, %(country)s, %(website)s, %(contact_name)s, %(contact_title)s, %(email)s, %(job_position)s, %(phone)s, %(mobile)s, %(line_id)s, %(age)s, %(customer_budget)s, %(product_interest)s, %(invoice_total)s, %(status)s, %(priority)s, %(salesperson)s, %(sales_team)s, %(tags)s, %(internal_notes)s, %(source)s, %(platform_id)s, %(assigned_user_id)s, %(created_at)s, %(updated_at)s) RETURNING lead.id]
[parameters: {'name': 'string', 'probability': 0.0, 'company_name': 'string', 'street': 'string', 'street2': 'string', 'city': 'string', 'state': 'string', 'zip_code': 'string', 'country': 'string', 'website': 'string', 'contact_name': 'string', 'contact_title': 'string', 'email': 'string', 'job_position': 'string', 'phone': 'string', 'mobile': 'string', 'line_id': 'string', 'age': 0, 'customer_budget': 'RANGE_1', 'product_interest': 'string', 'invoice_total': 0.0, 'status': 'NEW', 'priority': 0, 'salesperson': 'string', 'sales_team': 'string', 'tags': 'string', 'internal_notes': 'string', 'source': 'string', 'platform_id': 'strin', 'assigned_user_id': None, 'created_at': datetime.datetime(2025, 6, 10, 6, 3, 56, 747373), 'updated_at': datetime.datetime(2025, 6, 10, 6, 3, 56, 747373)}]
(Background on this error at: https://sqlalche.me/e/20/f405) (Background on this error at: https://sqlalche.me/e/20/7s2a)
